version: "2"

run:
  allow-parallel-runners: true
  concurrency: 10
  timeout: 5m

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  default: none

  enable:
    - bodyclose
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - godot
    - govet
    - ineffassign
    - makezero
    - misspell
    - modernize
    - nilerr
    - noctx
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usetesting

  settings:
    errcheck:
      check-type-assertions: true
    revive:
      enable-default-rules: true
      rules:
        - name: redefines-builtin-id

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofumpt
    - goimports

  settings:
    gofumpt:
      module-path: github.com/terr4m/terraform-provider-utils
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/terr4m/terraform-provider-utils

  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
